grails-app/controllers/ineed/MyaccountController.groovy
package ineed

import grails.plugin.springsecurity.SpringSecurityService

class MyaccountController {
    ItemService itemService
    SpringSecurityService springSecurityService

    def index() {
        redirect(action: 'timeline')
    }

    def timeline() {
        def user = springSecurityService.currentUser
        if (user) {
            params.sort = params.sort ?: "dateCreated"
            params.order = params.order ?: "desc"
            params.max = params.max ?: "10"

            def itemList = Item.findAllByUser(user, params)
            [itemList: itemList, total: user.items.size()]
        }
    }

    def ajaxAddItem() {
//        println(params)
        String store = "Комус"
        Item newItem = itemService.createItem(params.name, params.vendorCode, params.quantity, params.link, store, params.reason)
        flash.message = "Сохранено: ${newItem.item_name}"
        redirect(action: 'timeline')
    }
}

grails-app/views/myaccount/_newNote.gsp
<div id="newPost">

%{--<input id="charLeft" name="charLeft" size="5" value="160" readonly="true"/>--}%
<p>

<div class="h3" align="center">
    %{--<h4 align="center">--}%
    Что изволите?
    %{--</h4>--}%
</div>
</p>

<g:if test="${flash.message}">
    <div class="alert alert-danger" role="alert" align="center">
        ${flash.message}
    </div>
</g:if>

<p>


%{--<g:form action="ajaxAdd">--}%
<g:form action="ajaxAddItem" class="form-horizontal">
    <div class="container-fluid">
        <fieldset>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Наименование</label>

                <div class="col-md-5">
                    <input id="name" name="name" type="text" placeholder="например, слуховой аппарат"
                           class="form-control input-md" required="">
                    <span class="help-block">Вбиваете буковки с клавиатурки</span>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="vendorCode">Артикул</label>

                <div class="col-md-5">
                    <input id="vendorCode" name="vendorCode" type="text" placeholder="Например, 66613"
                           class="form-control input-md">
                    <span class="help-block">Если не знаете - ничего страшного. Необязательное поле</span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="quantity">Количество</label>

                <div class="col-md-5">
                    <input id="quantity" name="quantity" type="text" placeholder="Например, 1 шт. или 10 кг"
                           class="form-control input-md">
                    <span class="help-block">Требуемое количество</span>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="reason">Назначение</label>

                <div class="col-md-5">
                    <input id="reason" name="reason" type="text" placeholder="например, чтобы измерять углы стола"
                           class="form-control input-md">
                    <span class="help-block">зачем?</span>
                </div>
            </div>


            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="reason">Компания</label>

                <div class="col-md-5">
                    <input id="company" name="company" type="text" placeholder="ООО ОЛБО"
                           class="form-control input-md">
                    <span class="help-block">Для какой компании?</span>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="payment_method">Компания</label>

                <div class="col-md-5">
                    <input id="payment_method" name="payment_method" type="text" placeholder="Безналичный расчет, касса, Ф"
                           class="form-control input-md">
                    <span class="help-block">Метод оплаты</span>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="link">Ссылка</label>

                <div class="col-md-5">
                    <input id="link" name="link" type="text" placeholder="Например, http://paypal.me/theendcomplete/666"
                           class="form-control input-md">
                    <span class="help-block">Ссылка на товар, если уже нашли сами</span>
                </div>
            </div>

            <div class="col-md-12" align="center">
                <button id="saveButton" name="saveButton" class="btn btn-primary">Сохранить</button>
            </div>
        </fieldset>

    </div>
</g:form>



<g:javascript>
    function clearPost(e) {
        $('postContent').value = ''
    }
    function showSpinner(visible) {
        $('spinner').style.display = visible ? "inline" : "none"
    }

</g:javascript>

</p>
</div>

grails-app/views/myaccount/_noteEntries.gsp
%{--<asset:javascript src="jquery.js"/>--}%
<tr onclick='document.location = "<g:createLink controller="item" action='show' id='${it.id}'/>" '>
<td>${it.item_name}</td>
<td>${it.vendorCode}</td>
<td>${it.quantity}</td>
<td>${it.link}</td>
<td>${it.store}</td>
%{--<td>${it.item_status}</td>--}%
<td>${it.reason}</td>
<td>${it.company}</td>
<td>${it.payment_method}</td>
<td>${it.dateCreated}</td>
<td>${it.lastUpdated}</td>
<td align="center">
    %{--<g:test if="${!it.resolution}">--}%
    <span class="label label-success">${it.item_status = it.item_status ?: it.itemList}</span>
    %{--params.order = params.order ?: "desc"--}%
    %{--${it.item_status}--}%
</td>
</tr>







<script type="text/javascript" language="javascript" class="init">
    $(".clickable").on("click", function (e) {
        e.preventDefault();
        window.location = "/item/show/" + $(this).data("id");
    });
</script>
%{--<g:javascript>--}%
%{--function clearPost(e) {--}%
%{--$('postContent').value = ''--}%
%{--}--}%
%{--function showSpinner(visible) {--}%
%{--$('spinner').style.display = visible ? "inline" : "none"--}%
%{--}--}%

%{--</g:javascript>--}%

grails-app/views/myaccount/timeline.gsp
<%@ page import="ineed.Item" %>
<html>
<head>
    %{--<title>MyTimeline for ${user.username}</title>--}%
    <meta name="layout" content="main"/>
    %{--<meta name="layout" content="main; charset=UTF-8"/>--}%
    %{--<meta http-equiv="Content-Type" content="text/html">--}%
    %{--<g:if test="${user.profile.skin}">--}%
    %{--<link rel="stylesheet" href="<g:createLinkTo dir='css' file='${user.profile.skin}.css'/>"/>--}%
    %{--</g:if>--}%
</head>

<body>

%{--<g:render template="newNote" collection="${serviceNoteList}"/>--}%
<g:render template="newNote"/>
<p>

    %{--<h4 align="center">История запросов</h4>--}%

<div class="h4" align="center">История запросов</div>
</p>
<p>

<div id="allPosts">
    <div class="container" id="table">
        <div class="row">
            <div class="span5">
                %{--<table class="table table-striped table-condensed">--}%
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th>Наименование</th>
                        <th>Артикул</th>
                        <th>Количество</th>
                        <th>Ссылка</th>
                        <th>Поставщик</th>
                        %{--<th>Статус</th>--}%
                        <th>Назначение</th>
                        <th>Компания</th>
                        <th>Метод оплаты</th>
                        <th>Дата создания</th>
                        <th>Дата изменения</th>
                        <th>Статус</th>
                    </tr>
                    </thead>
                    <tbody>

                    <g:render template="noteEntries" collection="${itemList}"/>

                    </tbody>
                </table>

                <div class="pagination">
                    <g:paginate controller="myaccount" action="timeline" total="${total}" max="10"/>
                </div>
            </div>
        </div>
    </div>

</div>
</p>

%{--<g:paginate total="${postCount}"/>--}%
%{--<g:paginate total="${2}"/>--}%

</body>
</html>